/**
 * Datos Iniciales y de Demostración para FinPulse
 * Proporciona datos de prueba inmediatos para que la aplicación funcione al 100% desde el primer segundo.
 */
import { Account, Transaction, SavingsGoal } from "@/types";

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: "acc-1",
    userId: "demo-user",
    name: "Galicia Débito",
    accountType: "bank",
    balance: 245800.00,
    colorHex: "#3b82f6",
  },
  {
    id: "acc-2",
    userId: "demo-user",
    name: "MercadoPago",
    accountType: "wallet",
    balance: 89450.50,
    colorHex: "#8b5cf6",
  },
  {
    id: "acc-3",
    userId: "demo-user",
    name: "Visa Santander",
    accountType: "credit_card",
    balance: -142300.00, // Saldo consumido acumulado en la tarjeta
    closingDay: 20,
    dueDay: 30,
    colorHex: "#06b6d4",
    cardNetwork: "visa",
    lastFourDigits: "4812",
  },
  {
    id: "acc-4",
    userId: "demo-user",
    name: "Efectivo en Mano",
    accountType: "cash",
    balance: 35000.00,
    colorHex: "#10b981",
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    userId: "demo-user",
    accountId: "acc-1",
    accountName: "Galicia Débito",
    type: "expense",
    amount: 32400.00,
    category: "supermercado",
    description: "Compras Semanales Coto",
    notes: "Comestibles y artículos de limpieza",
    isAntExpense: false,
    installmentsTotal: 1,
    installmentCurrent: 1,
    transactedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: "tx-2",
    userId: "demo-user",
    accountId: "acc-3",
    accountName: "Visa Santander",
    type: "expense",
    amount: 75000.00,
    category: "compras_ropa",
    description: "Zapatillas Deportivas",
    notes: "Compradas en 3 cuotas fijas",
    isAntExpense: false,
    installmentsTotal: 3,
    installmentCurrent: 1,
    statementDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 15).toISOString(),
    transactedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "tx-3",
    userId: "demo-user",
    accountId: "acc-2",
    accountName: "MercadoPago",
    type: "expense",
    amount: 3800.00,
    category: "cafe_kiosco",
    description: "Café con medialunas al paso",
    notes: "Antojo de media tarde",
    isAntExpense: true,
    installmentsTotal: 1,
    installmentCurrent: 1,
    transactedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "tx-4",
    userId: "demo-user",
    accountId: "acc-1",
    accountName: "Galicia Débito",
    type: "income",
    amount: 850000.00,
    category: "salario",
    description: "Sueldo Mensual",
    notes: "Cobro del mes en curso",
    isAntExpense: false,
    installmentsTotal: 1,
    installmentCurrent: 1,
    transactedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
];

export const INITIAL_GOALS: SavingsGoal[] = [
  {
    id: "goal-1",
    creatorId: "demo-user",
    title: "Vacaciones Brasil 2027",
    targetAmount: 1200000.00,
    currentAmount: 780000.00,
    targetDate: "2027-01-15",
    isCollaborative: true,
    inviteCode: "FIN-BR2027",
    members: [
      {
        id: "gm-1",
        goalId: "goal-1",
        userId: "demo-user",
        userName: "Tú",
        contributedAmount: 480000.00,
        percentageContribution: 61.5,
        joinedAt: new Date().toISOString(),
      },
      {
        id: "gm-2",
        goalId: "goal-1",
        userId: "partner-user",
        userName: "Camila (Pareja)",
        contributedAmount: 300000.00,
        percentageContribution: 38.5,
        joinedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "goal-2",
    creatorId: "demo-user",
    title: "Fondo de Emergencia 3 Meses",
    targetAmount: 900000.00,
    currentAmount: 450000.00,
    targetDate: "2026-12-31",
    isCollaborative: false,
  },
];
